name: Unit tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Chryse
      uses: chryse-hdl/setup-chryse-action@v2

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Run tests
      run: sbt test
